# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: rowanmolony.com
tagline: Blog
description: |
  Hi there,
  I've spent the last four years working in software
  - full-stack web development, analytics & data pipelines -
  if any of that sounds interesting, you might find the posts here useful
url: https://www.rowanmolony.com
author: Rowan Molony
social:
  links:
    - https://github.com/rdmolony
    - https://www.linkedin.com/in/rowan-molony-113bbb155
google_site_verification: A_2d0sbemvD2kO6wMnmReN5Vnt5nBVOv6JZfsJGDoag

email: rowanmolony@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  rdmolony
linkedin_username: rowan-molony-113bbb155
rss: rss

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/:num/"

permalink: /blog/:year-:month-:day-:title.html

include:
  - _pages

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      image: /assets/images/headshot.png
      layout: "post"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
